apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-backend-config
  namespace: pfe-project
data:
  LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: defectdojo-config
  namespace: pfe-project
data:
  DD_ALLOWED_HOSTS: "*"
  DD_DJANGO_METRICS_ENABLED: "False"
  DD_INITIALIZE: "true"