apiVersion: v1
kind: Secret
metadata:
  name: defectdojo-secrets
  namespace: pfe-project
type: Opaque
stringData:
  DD_SECRET_KEY: "${DD_SECRET_KEY}"
  DD_CREDENTIAL_AES_256_KEY: "${DD_CREDENTIAL_AES_256_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: pfe-project
type: Opaque
stringData:
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"