apiVersion: v1
kind: Secret
metadata:
  name: defectdojo-secrets
  namespace: pfe-project
type: Opaque
stringData:
  
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: pfe-project
type: Opaque
stringData:
  POSTGRES_DB: "defectdojo"
  POSTGRES_USER: "defectdojo"
  POSTGRES_PASSWORD: "defectdojo"